### ISSUE TITLE
.DS_Store interrupts build process

### ISSUE THREAD

**Issue by MichaelPrecel** [arnoson/kirby-vite-multi-page-kit#1]
Love this plugin, thanks for bringing it into the world.

I noticed an issue Mac Catalina when building my site. I was getting an error:
`Could not resolve entry module (src/templates/.DS_Store/index.js).`

It seems the build process was looking for an index.js in the auto-generated DS Store file as though it were a folder. This was resolved by deleting the DS_Store file in src/templates/ via terminal (apparently these don't show up on Mac even if regular hidden files do anymore).

**Comment by arnoson** [comment]
Thanks for pointing this out! I'm not using a Mac so I haven't noticed, Ill have a look :)

**Comment by arnoson** [comment]
Should work now! Can you test the new version?

**Comment by MichaelPrecel** [comment]
@arnoson nice work, seems to be fully operational now!
