### ISSUE TITLE
localhost:3000 responds with a `404` after initial setup

### ISSUE THREAD

**Issue by owzim** [arnoson/kirby-vite-multi-page-kit#2]
composer: `2.1.8`
node: `v12.20.0`
os: macOS `10.14.6`

did everything like in the readme:

```sh
composer install
npm install
npm run dev
```

Just to make sure I even did a `npm run build` before.

**Comment by arnoson** [comment]
Are you visting `localhost:8888` or `localhost:3000` in the browser? Port 3000 is only vite's dev server for serving the assets, port 8888 ist the php dev server where kirby is running.

**Comment by arnoson** [comment]
Did this solve the issue @owzim?

**Comment by arnoson** [comment]
I'm closing this for now
